# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cstasker', '0002_auto_20171210_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'LocationBased')])),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('extra_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.TimeField()),
                ('action_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'Published'), (1, 'Refused'), (2, 'Accepted'), (3, 'Finish'), (4, 'UnFinish')])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstasker.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
