# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0003_task_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='action_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='publish_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
