# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='user_choice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
