# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='action_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='publish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Refused'), (2, 'Accepted'), (3, 'Finish'), (4, 'UnFinish')], null=True),
        ),
    ]
