# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0008_auto_20180508_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionnaire',
            old_name='qn_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='userquestionnaire',
            old_name='u_id',
            new_name='user',
        ),
    ]
