# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0009_auto_20180508_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qn_id',
            new_name='questionnaire',
        ),
    ]
