# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0012_batteryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicalrecord',
            name='net_info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
