# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0013_periodicalrecord_net_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanteenLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_count', models.IntegerField(blank=True, null=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cstasker.Canteen')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
