# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0016_voicerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicerecord',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
