# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-27 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cstasker', '0017_auto_20180527_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ax', models.FloatField(blank=True, null=True)),
                ('ay', models.FloatField(blank=True, null=True)),
                ('az', models.FloatField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='movingrecord',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
