# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-07 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0020_auto_20180606_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='choices',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
