# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-07 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstasker', '0021_userchoice_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
